#!/usr/bin/env bash

source defs.sh

declare -a deps=(libodb libodb-mysql vxl InsightToolkit)

for branch in "${branches[@]}"
do
    target=$branch"-ralph-x86_64"
    echo "Building target "$target
    
    ## Initialize buildroot
    mock init -r $target
    
    # Build and install required software from the internal repository
    build_if_not_already $branch $target libodb -1.4.0-1
    
    # Install other packages
    for dep in "${deps[@]}"
    do
	build_if_not_already $branch $target $dep
    done
done


