#!/usr/bin/env bash

source defs.sh

declare -a deps=(libodb libodb-mysql vxl InsightToolkit ITK-BinaryAttributeMorphology)

for target in "${targets[@]}"
do
    echo "Building target "$target
    
    ## Initialize buildroot
    mock init -r $target
    
#    # Build and install required software from the internal repository
    build_if_not_already $target libodb -1.4.0-1
    
#    # Expire yum cache manually so it is forced to re-download it at next step
#    yum --installroot /var/lib/mock/$target/root/ --setopt=tsflags=nocontexts clean metadata
    
#    # Install from a fresh copy of the cache. If it doesn't work fail.
#    mock -r $target install libodb-devel
    
#    if [ ! "$?" -eq $SUCCESS ]
#    then
#	echo "Problem installing libodb. Please check."
#	echo "Dependency build aborted"
#	exit
#    fi
    
    # Install other packages
    for dep in "${deps[@]}"
    do
	build_if_not_already $target $dep
	# Expire yum cache manually so it is forced to re-download it at next step
        yum --installroot /var/lib/mock/$target/root/ --setopt=tsflags=nocontexts clean all
	# Install from a fresh copy of the cache. If it doesn't work fail.
        mock -r $target install $dep-devel
    
        if [ ! "$?" -eq $SUCCESS ]
	then
	    echo "Problem installing "$dep". Please check!"
	    echo "Dependency build aborted."
	    exit
        fi

    
    done
done


