#!/usr/bin/env bash
source defs.sh

IFS=",$IFS"
for target in "${targets[@]}"
do
    for rd in "${rpmdir[@]}"
    do
	mkdir -pv $repoLocalDir/$target/$rd
	createrepo $repoLocalDir/$target/$rd
    done
done
