#!/bin/bash

base="http://mrceresa.fedorapeople.org"

declare -a srpms=(libodb-1.4.0-1.src.rpm libodb-mysql-1.4.0-1.src.rpm vxl-1.14.0-1.fc15.src.rpm InsightToolkit-3.20.1-1.fc15.src.rpm)

mkdir -p ~/rpmbuild/SRPMS/

for a in "${srpms[@]}"
do
    pushd ~/rpmbuild/SRPMS/
    wget $base/$a
    popd
done