#!/usr/bin/env bash

source defs.sh

# Delete old builds
rm -rf ralph-filters
##### Create tarball from last revision
git clone git@github.com:mrceresa/cfilters.git ralph-filters
filtersRev=$(date +%F | sed s/'-'/''/g)'git'
tar -czf ralph_filters.tar.gz ralph-filters

##### Build the source rpm
mv ralph_filters.tar.gz $HOME/rpmbuild/SOURCES/

# Clean old rpms
#rm SRPMS/ralph* RPMS/x86_64/ralph*
# Sed the spec to change version as appropriate!
newRev='Release:\t\t'$filtersRev
sed s/^Release.*/$newRev/ ralph-filters.spec.in > ralph-filters.spec
spec_dir=$(pwd)

# Generate the SRPM
pushd $HOME/rpmbuild/
rpmbuild -bs $spec_dir/ralph-filters.spec

popd

# Copy binary rpms to repo dir
#for target in "${targets[@]}"
#do
#    build_if_not_already $target ralph-filters
#done

