#!/usr/bin/env bash

source defs.sh

# Delete old builds
rm -rf ralph-core
#### Create tarball from last revision
git clone git@github.com:mrceresa/solidify.git ralph-core
coreRev=$(date +%F | sed s/'-'/''/g)'git'
tar -czf ralph_svn.tar.gz ralph-core

#### Build the source rpm
mv ralph_svn.tar.gz $HOME/rpmbuild/SOURCES/

pushd $HOME/rpmbuild/

# Clean old packages
rm SRPMS/ralph* RPMS/x86_64/ralph*
# Sed the spec to change version as appropriate!
newRev='Release:\t\t'$coreRev
sed s/^Release.*/$newRev/ SPECS/ralph-core.spec.in > SPECS/ralph-core.spec
# Generate the SRPM
rpmbuild -bs SPECS/ralph-core.spec

popd

#### Build the binary rpm
for target in "${targets[@]}"
do
    build_if_not_already $target ralph-core
done
