#!/usr/bin/env bash
repoLocalDir=~/ralph_repo/repos
rpmbuildDir=~/rpmbuild/RPMS/
#declare -a branches=(fedora-13 fedora-14)
declare -a rpmdir=(i386 x86_64 noarch)
declare -a deps=(ralph)

# Delete old builds
rm -rf ralph-filters
# Create tarball from last svn revision
git clone git@github.com:mrceresa/cfilters.git ralph-filters

filtersRev=$(date +%F | sed s/'-'/''/g)'git'

# Create tarballs
tar -czf ralph_filters.tar.gz ralph-filters

# Build and check the package
mv ralph_filters.tar.gz $HOME/rpmbuild/SOURCES/

pushd $HOME/rpmbuild/
rm SRPMS/ralph* RPMS/x86_64/ralph*

# Sed the spec to change version as appropriate!

newRev='Release:\t\t'$filtersRev
sed s/^Release.*/$newRev/ SPECS/ralph-filters.spec.in > SPECS/ralph-filters.spec

rm -rf /home/mario/rpmbuild/SRPMS/ralph-filters*.src.rpm
rpmbuild -bs SPECS/ralph-filters.spec
popd

mock rebuild --no-clean -r fedora-14-ralph-x86_64 /home/mario/rpmbuild/SRPMS/ralph-filters*.src.rpm
find /var/lib/mock/fedora-14-ralph-x86_64/result/ -name "ralph-filters*.rpm" -exec cp {} $repoLocalDir/fedora-14/x86_64/ \;
mock rebuild --no-clean -r fedora-15-ralph-x86_64 /home/mario/rpmbuild/SRPMS/ralph-filters*.src.rpm
find /var/lib/mock/fedora-15-ralph-x86_64/result/ -name "ralph-filters*.rpm" -exec cp {} $repoLocalDir/fedora-15/x86_64/ \;

./update_repo

# Copy binary rpms to repo dir
#for a in "${rpmdir[@]}"
#do
#    for dep in "${deps[@]}"
#    do
#        ##echo "find $rpmbuildDir$a -name $dep\* -exec cp {} $repoLocalDir/fedora-14/$a/ \;"
#        find /var/lib/mock/fedora-14-x86_64/result/ -name $dep\* -exec cp {} $repoLocalDir/fedora-14/$a/ \;
#        find /var/lib/mock/fedora-15-x86_64/result/ -name $dep\* -exec cp {} $repoLocalDir/fedora-15/$a/ \;
#    done
#done

