#!/usr/bin/env bash

source defs.sh

# Delete old builds
rm -rf ralph-core
#### Create tarball from last revision
git clone git@github.com:mrceresa/solidify.git ralph-core
coreRev=$(date +%F | sed s/'-'/''/g)'git'
tar -czf ralph_svn.tar.gz ralph-core

#### Build the source rpm
mv ralph_svn.tar.gz $HOME/rpmbuild/SOURCES/

# Sed the spec to change version as appropriate!
newRev='Release:\t\t'$coreRev
sed s/^Release.*/$newRev/ ralph-core.spec.in > ralph-core.spec
spec_dir=$(pwd)

pushd $HOME/rpmbuild/

## Clean old packages
#rm SRPMS/ralph* RPMS/x86_64/ralph*
# Generate the SRPM
rpmbuild -bs $spec_dir/ralph-core.spec

popd

#### Build the binary rpm
for branch in "${branches[@]}"
do
    target=$branch"-ralph-x86_64"
    build_if_not_already $branch $target ralph-core
done
