#!/usr/bin/env bash
repoDir=/var/www/fedora
repoLocalDir=~/ralph_repo/repos
repoName=cil
declare -a branch=(fedora-14 fedora-15)
declare -a rpmdir=(i386 x86_64 noarch SRPMS)
declare -a rsyncParam=(-avtz --delete)

cd $repoLocalDir
for dir2 in "${branch[@]}"
do
    echo -e "\033[31mUpdate $dir2 repos:\033[0m"
    cd $dir2
    for dir3 in "${rpmdir[@]}"
    do
        echo -e "\033[34m\t* $dir3:\033[0m"
        cd $dir3
        createrepo ./
        rsync "${rsyncParam[@]}" ./* $repoDir/$repoName/$dir2/$dir3
        cd ..
    done
    cd ..
done
cd ..
