#!/usr/bin/env bash
source defs.sh

declare -a rsyncParam=(-avtz --delete)

pushd $repoLocalDir
for dir2 in "${targets[@]}"
do
    echo -e "\033[31mUpdate $dir2 repos:\033[0m"
    cd $dir2
    for dir3 in "${rpmdir[@]}"
    do
        echo -e "\033[34m\t* $dir3:\033[0m"
        cd $dir3
        echo rsync "${rsyncParam[@]}" ./* $repoDir/$dir2/$dir3
        rsync "${rsyncParam[@]}" ./* $repoDir/$dir2/$dir3
        cd ..
    done
    cd ..
done
popd
