#!/usr/bin/env bash
source defs.sh

declare -a rsyncParam=(-avtz --delete)

pushd $repoDir
for dir2 in "${targets[@]}"
do
    echo -e "\033[31mUpdate $dir2 repos:\033[0m"
    cd $dir2
    for dir3 in "${rpmdir[@]}"
    do
        echo -e "\033[34m\t* $dir3:\033[0m"
        cd $dir3
#	rm -rf repodata/
	createrepo ./
        cd ..
    done
    cd ..
done
popd
